# Generated by Django 4.2.30 on 2026-07-04 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('is_high_risk', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['country'], name='customers_c_country_fc020b_idx'), models.Index(fields=['is_high_risk'], name='customers_c_is_high_254f4e_idx')],
            },
        ),
    ]
