# Generated by Django 4.2.30 on 2026-07-04 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('TRANSACTION_CREATED', 'Transaction Created'), ('RISK_ANALYSIS', 'Risk Analysis'), ('STATUS_UPDATED', 'Status Updated')], max_length=50)),
                ('actor', models.CharField(default='SYSTEM', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
